version: '3'
services:
  golang_test:
    build:
      context: ./golang
      dockerfile: ./Dockerfile
    restart: on-failure
    #command: /bin/sh entrypoint.sh
    volumes:
      - ./golang:/usr/src/app/
      - ./scripts/entrypoint.sh:/usr/src/app/entrypoint.sh
    networks:
      - monorepo_net
#  nodejs_test:
#    build:
#      context: ./nodejs
#      dockerfile: ./Dockerfile
#    restart: on-failure
#    command: /bin/sh entrypoint.sh
#    volumes:
#      - ./nodejs:/usr/src/app/
#      - /usr/src/app/node_modules
#      - ./scripts/entrypoint.sh:/usr/src/app/entrypoint.sh
#    networks:
#      - monorepo_net

networks:
  monorepo_net:
    driver: bridge
