version: '3'
services:
  calypso:
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/calypso/
    environment:
      - PORT=3001
      - APP_NAME=calypso
    ports:
      - 8001:3001
    restart: on-failure
    volumes:
      - calypso_vol:/usr/src/calypso/
    networks:
      - monorepo_net
  echo:
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/echo/
    environment:
      - PORT=3001
      - APP_NAME=echo
    ports:
      - 8002:3001
    restart: on-failure
    volumes:
      - echo_vol:/usr/src/echo/
    networks:
      - monorepo_net
  frontend:
    build:
      context: ./nodejs
      dockerfile: ./Dockerfile.angular
      args:
        project: frontend
    ports:
      - 8000:80
    restart: on-failure
    volumes:
      - frontend_vol:/usr/src/frontend/
      - node_modules:/usr/src/frontend/node_modules/
    networks:
      - monorepo_net
  ocean:
    build:
      context: ./nodejs
      dockerfile: ./Dockerfile.nest
      args:
        project: ocean
    ports:
      - 8003:3333
    restart: on-failure
    volumes:
      - ocean_vol:/usr/src/ocean/
      - node_modules:/usr/src/ocean/node_modules/
    networks:
      - monorepo_net

volumes:
  calypso_vol:
  echo_vol:
  frontend_vol:
  ocean_vol:
  node_modules:

networks:
  monorepo_net:
    driver: bridge
