version: '3'
services:
  calypso:
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        port: 3001
        src: ./cmd/calypso/
    ports:
      - 8080:3001
    restart: on-failure
    volumes:
      - calypso_vol:/usr/src/calypso/
    networks:
      - calypso_net

volumes:
  calypso_vol:

networks:
  calypso_net:
    driver: bridge
