version: 2
jobs:
  build:
    docker:
      - image: cibuilds/docker
    working_directory: ~/fullstack-monorepo/
    steps:
      - checkout
      - setup_remote_docker:
      - run: make test
      - run: make build-prod
