version: 2
jobs:
  build:
    docker:
      - image: golang:1.13.5-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: make image
      - run: make test
      - run: make clean
