version: 2

test_calypso:


jobs:
  build:
    working_directory: /go/src/github.com/fulls1z3/fullstack-monorepo/
    steps:
      - checkout
      - run: make image
      - run: make test
      - run: make clean
