# Start from node base image
FROM node:12-alpine as builder

# Set the current working directory inside the container
WORKDIR /test

# Copy package.json, yarn.lock files and download deps
COPY package.json yarn.lock ./
RUN yarn global add @angular/cli
RUN yarn

# Copy sources to the working directory
COPY . .

# Run the test suite
ARG project
RUN ng test $project
